### ISSUE TITLE
CurlResponse 仍然报错

### ISSUE THREAD

**Issue by lixworth** [minbaby/hyperf-sentry#11]
```
[2021-10-05 19:24:33] sentry.ERROR: Failed to send the event to Sentry. Reason: "curl_setopt(): Argument #1 ($handle)
must be of type Swoole\Coroutine\Curl\Handle,
 null given". {"exception":"[object] (TypeError(code: 0): curl_setopt(): Argument #1 ($handle) must be of 
 type Swoole\\Coroutine\\Curl\\Handle, null given at
 /home/lixworth/Project/hyperf-mfuns/vendor/symfony/http-client/Response/CurlResponse.php:75)",
 "event":{"Sentry\\Event":[]}} []
```

* hyperf 2.2 
* sentry/sdk 3.1.0
* sentry/sentry 3.3.3
* swoole 4.7.1
* sym http-client v5.3.8

**Comment by lixworth** [comment]
已解决
 swoole 4.7.1 需这样修改 SWOOLE_HOOK_FLAGS
````
#bin/hyperf.php
! defined('SWOOLE_HOOK_FLAGS') && define('SWOOLE_HOOK_FLAGS', SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_NATIVE_CURL);
````

**Comment by minbaby** [comment]
> 已解决 swoole 4.7.1 需这样修改 SWOOLE_HOOK_FLAGS
> 
> ```
> #bin/hyperf.php
> ! defined('SWOOLE_HOOK_FLAGS') && define('SWOOLE_HOOK_FLAGS', SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_NATIVE_CURL);
> ```

你编译的时候应启用  `--enable-swoole-curl` 了吗, 我之前试的时候，最新版版本启用那个参数，就可以完美支持，对于老版本或者没有启用那个命令的话，只能使用 `^SWOOLE_HOOK_CURL `, 来关闭curl hook了。

**Comment by lixworth** [comment]
> > 已解决 swoole 4.7.1 需这样修改 SWOOLE_HOOK_FLAGS
> > ```
> > #bin/hyperf.php
> > ! defined('SWOOLE_HOOK_FLAGS') && define('SWOOLE_HOOK_FLAGS', SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_NATIVE_CURL);
> > ```
> 
> 你编译的时候应启用 `--enable-swoole-curl` 了吗, 我之前试的时候，最新版版本启用那个参数，就可以完美支持，对于老版本或者没有启用那个命令的话，只能使用 `^SWOOLE_HOOK_CURL `, 来关闭curl hook了。

emm 我是使用的 pecl install 的 并选择 curl yes 按理来说是不就开启了
并且phpinfo中也显示是开启
![image](https://user-images.githubusercontent.com/22554300/137120319-13ead57a-fc73-43fe-9c42-6d273da42904.png)

接下来我也复现了 SWOOLE_HOOK_ALL  时执行 sentry:test
仍出现如下错误

``
[2021-10-13 18:59:11] sentry.ERROR: Failed to send the event to Sentry. Reason: "curl_setopt(): Argument #1 ($handle) must be of type Swoole\Coroutine\Curl\Handle, null given". {"exception":"[object] (TypeError(code: 0): curl_setopt(): Argument #1 ($handle) must be of type Swoole\\Coroutine\\Curl\\Handle, null given at /home/lixworth/Project/hyperf-mfuns/vendor/symfony/http-client/Response/CurlResponse.php:75)","event":{"Sentry\\Event":[]}} []
``

![image](https://user-images.githubusercontent.com/22554300/137120793-cf3b7bb5-1e13-494f-ae14-27e5dbab9d2a.png)

**很抱歉 目前我还没时间测试手动编译是否有这个问题（**
