### ISSUE TITLE
`class_map` 配置不对，应该是 `annotations.scan.class_map`

### ISSUE THREAD

**Issue by huangdijia** [minbaby/hyperf-sentry#15]
https://github.com/minbaby/hyperf-sentry/blob/4ba5ac6b4d34f2bc07176ec0f0234900ccf8569a/src/ConfigProvider.php#L23-L30

**Comment by minbaby** [comment]
https://hyperf.wiki/3.0/#/zh-cn/upgrade/1.1?id=%e8%b0%83%e6%95%b4%e8%87%aa%e5%ae%9a%e4%b9%89%e7%bb%84%e4%bb%b6%e7%9a%84-configprovider

确认了一下，1.0 升级 1.1 的时候这个没有更新，等会我去更新一下

**Comment by minbaby** [comment]
已经修复了，你试一下OK不

**Comment by huangdijia** [comment]
👌

**Comment by huangdijia** [comment]
你这个包支持协程风格？

**Comment by minbaby** [comment]
可以试一下，hyperf 默认不就是在携程下工作的吗？不清楚你的场景是哪个

**Comment by huangdijia** [comment]
协程风格指的是 server 的风格

**Comment by minbaby** [comment]
![image](https://user-images.githubusercontent.com/3191858/220505171-3a7a4af9-0c38-4aae-b79f-52c9aa631f42.png)

![image](https://user-images.githubusercontent.com/3191858/220505211-b1e85ccb-a366-412e-a9a8-0565dfb7a0ad.png)

刚试了一下，基础用法是ok的，还有个路径写错了，我要先更新一下

**Comment by huangdijia** [comment]
协程风格应该是有坑的

**Comment by minbaby** [comment]
能说一下会出现什么问题吗？ 有demo就更好了

**Comment by huangdijia** [comment]
你在项目中安装 `hyperf/metric`，然后在请求抛个异常就知道了，面包屑里有大量因为 metric 的 poolWatcher 产生的数据，这个跟请求没有关系。

**Comment by huangdijia** [comment]
分享增加未开启 native-curl 支持：https://github.com/friendsofhyperf/sentry/releases/tag/v3.0.30

**Comment by minbaby** [comment]
> 分享增加未开启 native-curl 支持：https://github.com/friendsofhyperf/sentry/releases/tag/v3.0.30

感谢分享

**Comment by huangdijia** [comment]
可以加个联系方式交流一下？

**Comment by minbaby** [comment]
> 可以加个联系方式交流一下？

好，我邮件给你
