### ISSUE TITLE
升级hyperf到2.1遇到的问题，请问如何兼容处理

### ISSUE THREAD

**Issue by suandaode** [minbaby/hyperf-sentry#5]
minbaby/hyperf-sentry v2.0.0 requires hyperf/framework 2.0.* -> found hyperf/framework[v2.0.0, v2.0.3, v2.0.11, 2.0.x-dev] but it conflicts with your root composer.json require (2.1.*)

**Comment by minbaby** [comment]
抽时间我更新一下试试看 #7
